import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: ['src/index.ts'],
    format: ['cjs', 'esm'],
    target: 'es2022',
    platform: 'neutral',
    dts: true,
    sourcemap: true,
    clean: true,
    treeshake: true,
  },
  {
    entry: ['src/next.ts'],
    format: ['cjs', 'esm'],
    target: 'es2022',
    platform: 'neutral',
    dts: true,
    sourcemap: true,
    clean: false,
    treeshake: true,
  },
  {
    entry: ['src/react.tsx'],
    format: ['cjs', 'esm'],
    target: 'es2022',
    platform: 'neutral',
    dts: true,
    sourcemap: true,
    clean: false,
    treeshake: false,
    external: ['react', 'react/jsx-runtime'],
    banner: { js: "'use client';" },
  },
  {
    entry: ['src/vue.ts'],
    format: ['cjs', 'esm'],
    target: 'es2022',
    platform: 'neutral',
    dts: true,
    sourcemap: true,
    clean: false,
    external: ['vue'],
  },
  {
    entry: ['src/svelte.ts'],
    format: ['cjs', 'esm'],
    target: 'es2022',
    platform: 'neutral',
    dts: true,
    sourcemap: true,
    clean: false,
    external: ['svelte'],
  },
  {
    entry: ['src/angular.ts'],
    format: ['cjs', 'esm'],
    target: 'es2022',
    platform: 'neutral',
    dts: true,
    sourcemap: true,
    clean: false,
    external: ['@angular/core'],
  },
  {
    entry: ['src/solid.ts'],
    format: ['cjs', 'esm'],
    target: 'es2022',
    platform: 'neutral',
    dts: true,
    sourcemap: true,
    clean: false,
    external: ['solid-js'],
  },
]);
